AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Metrics/BlockLength:
  Exclude:
    - spec/*
